isomerpages/moe-bendemeerpri

- _about-us/Aspire Newsletter.md
Aspire newsletter for 2022 updates
> Update file: Aspire Newsletter.md

- _our-people/Teaching Staff/Primary 4 Teachers.md
> Update file: Primary 4 Teachers.md

- _our-people/Teaching Staff/Primary 3 Teachers.md
> Update file: Primary 3 Teachers.md

- _our-people/School Advisory Committee (SAC).md
> Update file: School Advisory Committee (SAC).md

- _about-us/Principal's Message.md
> Update file: Principal's Message.md

- _curriculum/School Library/Overview.md
> Update file: Overview.md

- pages/Announcements.md
> Pls see. Thanks

- _about-us/Aspire Newsletter.md
> Fyna pls. Tks

- _about-us/MOE Kindergarten.md
- _about-us/collection.yml
> removed outdatd MK Webpage

- _mk-at-bendemeer/KCare at Bendemeer.md
- _mk-at-bendemeer/Registration and Fees.md
> MK Updates

- _mk-at-bendemeer/MK Team.md
> Mk team update

- _our-people/Teaching Staff/Mother Tongue Teachers.md
> Change in tamil teacher

- _our-people/Non Teaching Staff.md
> Added new ICT associate

- _links/Teachers.md
#Explore ICT @ BPS link has been changed.
> Link changes

- _our-people/Executive Committee (EXCO).md
- _our-people/Teaching Staff/Mother Tongue Teachers.md
- _our-people/Teaching Staff/Primary 6 Teachers.md
Removed Amily and Kwang Yee's name
> Staff Update

- _our-people/Teaching Staff/Mother Tongue Teachers.md
- _our-people/Teaching Staff/Primary 1 Teachers.md
- _our-people/Teaching Staff/Primary 2 Teachers.md
- _our-people/Teaching Staff/Primary 3 Teachers.md
- _our-people/Teaching Staff/Primary 4 Teachers.md
- _our-people/Teaching Staff/Primary 6 Teachers.md
> P1 Teachers Update

- _our-people/Teaching Staff/Primary 1 Teachers.md
- _our-people/Teaching Staff/Primary 2 Teachers.md
- _our-people/Teaching Staff/Primary 3 Teachers.md
- _our-people/Teaching Staff/Primary 4 Teachers.md
- _our-people/Teaching Staff/Primary 5 Teachers.md
- _our-people/Teaching Staff/Primary 6 Teachers.md
> People Updates

- pages/Announcements.md
Updated announcements to include msg to alumni
> Updates in Announcements

- _school-information/School Services and Contacts/School Canteen Advertisement.md
> School Canteen Advertisement

- _cca/Niche CCAs/Chinese Dance.md
- _cca/Niche CCAs/Wushu.md
- _our-people/Executive Committee (EXCO).md
- _our-people/Teaching Staff/Mother Tongue Teachers.md
- _our-people/Teaching Staff/Primary 4 Teachers.md
Had to update the website with some updates
> Staff Names Updated

- _about-us/Our Achievements/CCA Awards.md
- _school-information/School Services and Contacts/School Uniform.md
> SChool Uniform updates

- pages/Announcements.md
> Changes to announcement pg

- _mk-at-bendemeer/Video & Photo Gallery.md
- _mk-at-bendemeer/collection.yml
- _our-people/Non Teaching Staff.md
- _our-people/Teaching Staff/Primary 2 Teachers.md
Kindly assist to approve the edit.
> Update of  school counsellor 

- index.md
> typo error in the front page

- _curriculum/English.md
- _our-people/Teaching Staff/Primary 1 Teachers.md
- _our-people/Teaching Staff/Primary 6 Teachers.md
Remove teacher from P6-R Lam ShuZhen who has been posted out.
> Update teaching staff

- _our-people/Executive Committee (EXCO).md
- _our-people/Non Teaching Staff.md
Update non-teaching staff list with OM Francis, SWO and OSO.
> Update staff list 

- _our-people/Teaching Staff/Primary 1 Teachers.md
Update Tr- najlaa_hameed_maricar@moe.edu.sg email add
> Update in trs's email

- _our-people/Executive Committee (EXCO).md
- _our-people/Non Teaching Staff.md
> remove sunny contact

- _our-people/For Parents.md
> changed 2023 to 2024

- _curriculum/English.md
> Update EL curriculum

- _about-us/Aspire Newsletter.md
- _about-us/Our Achievements/2024 Academic Awards (Term 1).md
- _ict/Cyber Wellness/Overview.md
- _links/Teachers.md
> broken links updated 

- _config.yml
- _data/footer.yml
> website updates

- _curriculum/English.md
Included P1 stories under English Curriculum
> P1 Stories

- _for-parents/Positive Parenting Programmes/Overview.md
- _our-people/For Parents.md
touch.org.sg has reorganized their website and it necessitate BPS to update the hyperlink to their relevant web page.
> Change of Hyperlink

- _our-people/Non Teaching Staff.md
To delete former OM Christopher Noel
> Update Staff Movement

- _school-information/School Services and Contacts/School Bookshop.md
> Booklists uploaded

- _ict/Cyber Wellness/How do I ensure my child uses their devices responsibly.md
- _our-people/Executive Committee (EXCO).md
Removed link that is no longer available
> Update Cyber Wellness Advice

- _our-people/Executive Committee (EXCO).md
- _our-people/Teaching Staff/Primary 3 Teachers.md
Update VP Linda Lau's and EO Chia Jia Min's email addresses
> Update email addressees

- _our-people/Teaching Staff/Primary 1 Teachers.md
> Update email address

- _for-parents/The Growing Years Programme for P5 & P6.md
- _links/Parents.md
Updated sexuality education and added link for parents briefing 2025.
> CCE Updates and Parents Briefing

- _for-parents/The Growing Years Programme for P5 & P6.md
Update date in para 9 from 2024 to 2025
> CCE Updates 

- _school-information/School Rules.md
> School Rules update 2025

- _mk-at-bendemeer/Video & Photo Gallery.md
> MK CNY 2025

- _mk-at-bendemeer/Video & Photo Gallery.md
> MK chinese new year Video

- _about-us/The Bendemeer Experience (e Open House).md
- _links/Parents.md
- _mk-at-bendemeer/2025 MK Openhouse.md
- _our-people/Executive Committee (EXCO).md
- _our-people/Non Teaching Staff.md
Pending HPB dental and vaccination consent form
> Update contact details and group Insurance matters

- _links/Students.md
- _links/Teachers.md
Removal of icons in Student, Teacher and Parent page.
> Rearrangement of items in Link pages

- _our-people/School Advisory Committee (SAC).md
> Update Title of SAC Member

- _our-people/Non Teaching Staff.md
- _school-information/School Services and Contacts/School Canteen Advertisement.md
> Sch Canteen 

- index.md
> School Calendar

- _links/Students.md
> Website Update -

- _links/Students.md
Updated website with MS Teams links under students
>  Microsoft Teams link

- _about-us/Principal's Message.md
> P message updated

- _about-us/The Bendemeer Experience (e Open House).md
> update to publcity page

- _our-people/Executive Committee (EXCO).md
- _our-people/Non Teaching Staff.md
- _our-people/Teaching Staff/Mother Tongue Teachers.md
- _our-people/Teaching Staff/Primary 2 Teachers.md
> remove names

- _cca/Niche CCAs/Floorball.md
> removed Ms Lei Jiajia from CCA

- _links/Students.md
updathe the name from all ears to check-in
> survey- updated naming

- _our-people/Non Teaching Staff.md
> Add- ICT manager

- _curriculum/English.md
- _links/Parents.md
- index.md
> Teachers Day

- _links/Students.md
> t4 survey link

- _links/Students.md
> updated the link for Term 4 Survey link

- _school-information/School Services and Contacts/School Canteen Advertisement.md
Update School Canteen Advertisement as requested by Adibah
> Update School Canteen Advertisement 

- _our-people/School Advisory Committee (SAC).md
- _school-information/School Services and Contacts/Dental Clinic.md
> Adding new SAC member
